FROM node
EXPOSE 8081
COPY . .
RUN npm install

ENV REACT_APP_SET_AUTH="firebase"

ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_DATABASE_URL
ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID

ENV REACT_APP_FIREBASE_API_KEY="${REACT_APP_FIREBASE_API_KEY}"
ENV REACT_APP_FIREBASE_AUTH_DOMAIN="${REACT_APP_FIREBASE_AUTH_DOMAIN}"
ENV REACT_APP_FIREBASE_DATABASE_URL="${REACT_APP_FIREBASE_DATABASE_URL}"
ENV REACT_APP_FIREBASE_STORAGE_BUCKET="${REACT_APP_FIREBASE_STORAGE_BUCKET}"
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID="${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}"

RUN npm run build

CMD npm run server
