FROM node
EXPOSE 8081
COPY . .
RUN npm install

ENV REACT_APP_SET_AUTH="firebase"
ENV REACT_APP_FIREBASE_API_KEY="AIzaSyC1lx2JmGe3m6K5sYGWDJE24Ra_1z5fftE"
ENV REACT_APP_FIREBASE_AUTH_DOMAIN="lykkeliapp.firebaseapp.com"
ENV REACT_APP_FIREBASE_DATABASE_URL="https://lykkeliapp.firebaseio.com"
ENV REACT_APP_FIREBASE_STORAGE_BUCKET="lykkeliapp.appspot.com"
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID="462703787524"

RUN npm run build

CMD npm run server
